# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44e9add45175e3a6fff445f746af38dc98fc1cbacc1a2c33979886b4b2d88d0424be3608bd6373586e8f43540bb7740e0a0c45129afdaac3e754fc43bf77a55f

test:
  secret_key_base: f485d7377599427db4914616af2f203c353025f785423288f12e3a615cbb9158bea2807ee0f8005fbaf6b6474519be8efe0945a3aec4f673e367dde29ea527ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
